import { UnitType } from '../types';

export const translations = {
  ur: {
    // App Header & Branding
    appTitle: 'آڑھت و منڈی بولی',
    appSubtitle: 'سبزی و فروٹ کمیشن مینجر',
    shopDefaultName: 'الحمراء فروٹ اینڈ سبزی کمیشن شاپ',
    shopAddressDefault: 'دکان نمبر ۴۵، نیو سبزی منڈی، لاہور',
    arhtiDefaultName: 'ملک محمد عرفان (آڑھتی)',

    // Tabs
    tabBolli: 'بولی و مال آمد',
    tabExpenses: 'اخراجات پرچی',
    tabReceipt: 'پرچی / بل',
    tabKhata: 'خریدار کھاتہ',
    tabReports: 'گوشوارہ و رپورٹس',
    tabHistory: 'روزنامچہ و منافع',
    tabSettings: 'سیٹنگز',

    // Reports Section
    reportsTitle: 'منڈی تفصیلی رپورٹس و گوشوارہ',
    reportsSubtitle: 'زمیندار، خریدار، تاریخ اور اجناس کے حساب سے حساب کتاب',
    reportByVendor: 'زمیندار وار رپورٹ',
    reportByCustomer: 'خریدار وار رپورٹ',
    reportByDate: 'تاریخ وار رپورٹ',
    reportByProduct: 'اجناس وار رپورٹ',
    dateRange: 'تاریخ کا انتخاب',
    allTime: 'ہمہ وقتی (تمام)',
    today: 'آج',
    yesterday: 'گزشتہ کل',
    last7Days: 'گزشتہ ۷ دن',
    thisMonth: 'موجودہ مہینہ',
    customRange: 'اپنی مرضی کی تاریخ',
    fromDate: 'شروع تاریخ',
    toDate: 'آخری تاریخ',
    exportCSV: 'ایکسل / CSV ڈاؤنلوڈ',
    printReport: 'رپورٹ پرنٹ کریں',
    shareReportWA: 'واٹس ایپ خلاصہ',
    avgRate: 'اوسط ریٹ',
    minRate: 'کم سے کم ریٹ',
    maxRate: 'زیادہ سے زیادہ ریٹ',
    totalUnitsSold: 'کل فروخت شدہ',
    totalLotsCount: 'کل لاٹس',
    cashCollected: 'نقد وصولی',
    creditOutstanding: 'بقایا ادھار',
    netVendorPayable: 'زمیندار کا میزان',
    netArhtiCommission: 'خالص آڑھت کمیشن',
    noReportsFound: 'منتخب کردہ فلٹر کے مطابق کوئی ریکارڈ نہیں ملا۔',

    // Customer Directory & Connect
    customerDirectory: 'خریدار ڈائریکٹری و رابطہ',
    addCustomer: 'نیا خریدار محفوظ کریں',
    editCustomer: 'خریدار ترمیم',
    customerSaved: 'خریدار محفوظ ہو گیا!',
    phoneCall: 'فون کال',
    whatsapp: 'واٹس ایپ میسج',
    recordPayment: 'رقم وصولی اندراج',
    paymentHistory: 'وصولیوں کا ریکارڈ',
    saveCustomerPrompt: 'اس خریدار کو ڈائریکٹری میں محفوظ کریں',
    shopOrMarket: 'دکان / منڈی کا پتہ',
    customerPhone: 'فون نمبر',
    selectSavedCustomer: 'محفوظ خریدار کا انتخاب کریں',

    // Custom Product ("Other")
    otherProduct: 'دیگر جنس',
    enterCustomProduct: 'اپنی مرضی کا پھل یا سبزی درج کریں',
    productUrduLabel: 'جنس کا نام (اردو میں)',
    productEnLabel: 'جنس کا نام (انگریزی)',
    selectIcon: 'ایموجی علامت',

    // Data Backup
    dataBackup: 'ڈیٹا بیک اپ و بحالی',
    downloadBackup: 'ڈیٹا بیک اپ ڈاؤنلوڈ (JSON)',
    restoreBackup: 'بیک اپ فائل بحال کریں',
    backupRestored: 'بیک اپ کامیابی سے بحال ہو گیا!',
    backupInvalid: 'غلط بیک اپ فائل۔',

    // Bolli / Lot Management
    newLot: 'نیا مال اندراج',
    activeLots: 'جاری بولیاں',
    completedLots: 'مکمل شدہ مال',
    viewAllLots: 'تمام لاٹس دیکھیں',
    viewMore: 'مزید دیکھیں',
    allLotsDirectory: 'تمام مال و لاٹس ڈائریکٹری',
    filterAll: 'تمام',
    filterNotSold: 'نہ بکا ہوا (تازہ)',
    filterPartiallySold: 'جزوی فروخت شدہ',
    filterFullySold: 'مکمل فروخت شدہ',
    filterDate: 'تاریخ',
    filterToday: 'آج',
    filterYesterday: 'گزشتہ کل',
    filterThisWeek: 'پچھلے 7 دن',
    filterAllDates: 'تمام تاریخیں',
    searchLotsPlaceholder: 'لاٹ نمبر، زمیندار، جنس، گاڑی، یا شہر تلاش کریں...',
    selectLot: 'بولی شروع کریں',
    lotStatus: 'حالت لاٹ',
    noLotsFound: 'کوئی لاٹ نہیں ملی',
    lotNumber: 'لاٹ نمبر',
    vendor: 'زمیندار / وینڈر',
    vendorName: 'نام زمیندار',
    vendorPhone: 'فون نمبر',
    vendorCity: 'شہر / علاقہ',
    saveVendorToDb: 'زمیندار کو ڈائریکٹری میں محفوظ کریں',
    selectSavedVendor: 'مستقل زمیندار:',
    saveCustomerToDb: 'گاہک کو کھاتہ ڈائریکٹری میں محفوظ کریں',
    walkInCustomer: 'عام گاہک (Walk-in)',
    walkInPlaceholder: 'عام گاہک (Walk-in) - نام اختیاری ہے',
    backToBolli: 'واپس بولی ہال',
    back: 'واپس',
    product: 'جنس / سبزی / پھل',
    unitType: 'قسم پیکنگ',
    totalQuantity: 'کل تعداد',
    remainingQuantity: 'باقی تعداد',
    soldQuantity: 'فروخت شدہ',
    vehicleNumber: 'گاڑی نمبر',
    arrivalDate: 'آمد تاریخ',
    rate: 'ریٹ فی عدد / کریٹ',
    startBolli: 'بولی شروع کریں',
    bolliProgress: 'بولی کی پیشرفت',
    allSold: 'تمام مال بک گیا',
    inProgress: 'بولی جاری ہے',

    // Units
    unitBori: 'بوری',
    unitTora: 'توڑہ / تورڑہ',
    unitKainchi: 'کینچی',
    unitShopper: 'شاپر',
    unitCrates: 'کریٹ',
    unitTheli: 'تھیلی',
    unitPeti: 'پیٹی',
    unitKg: 'کلوگرام',
    unitNag: 'نگ / عدد',

    // Bolli Bidding Form
    addBidSale: 'خریدار بولی اندراج',
    buyerName: 'خریدار / دکاندار کا نام',
    buyerPhone: 'فون',
    buyQuantity: 'خریداری تعداد',
    bidRate: 'بولی ریٹ (روپے)',
    totalAmount: 'کل رقم',
    paymentType: 'ادائیگی کی نوعیت',
    paymentCash: 'نقد وصول',
    paymentCredit: 'ادھار / کھاتہ',
    paymentPartial: 'جزوی نقد',
    confirmSale: 'بولی محفوظ کریں',
    salesList: 'فروخت شدہ لاٹ لسٹ',
    noSalesYet: 'ابھی کوئی بولی ریکارڈ نہیں ہوئی۔',

    // Mandi Expense Slip (Replicating user's photo)
    expenseSlipTitle: 'اخراجات پرچی و میزان',
    expenseSlipSubtitle: 'زمیندار کے اخراجات کی کٹوتی اور منافع کا حساب',
    grossTotal: 'ٹوٹل فروخت',
    expensesSection: 'اخراجات',
    commission: 'کمیشن',
    commissionAuto: 'کمیشن (فیصد یا فکسڈ)',
    kiraya: 'کرایہ گاڑی',
    mazdoori: 'مزدوری (اترائی و چنائی)',
    munshiana: 'منشیانہ',
    naqdAdvance: 'نقد / پیشگی رقم',
    marketFee: 'مارکیٹ فیس',
    customExpense: 'دیگر کٹوتی / خرچہ',
    addCustomExpense: 'نیا کٹوتی فیلڈ شامل کریں',
    expenseName: 'خرچے کا نام',
    amount: 'رقم',
    totalExpenses: 'کل اخراجات',
    meezan: 'میزان (خالص رقم زمیندار کے لیے)',
    arhtiProfit: 'آڑھتی کا خالص منافع (کمیشن)',
    adjustManual: 'دستی ترمیم کریں',
    resetDefault: 'خودکار حساب',

    // Receipt & Share
    printReceipt: 'پرچی پرنٹ کریں',
    shareWhatsApp: 'واٹس ایپ پر بھیجیں',
    copyReceipt: 'پرچی کاپی کریں',
    receiptCopied: 'پرچی کاپی ہو گئی!',
    pakkiParchi: 'پکی پرچی آڑھت',
    date: 'تاریخ',
    time: 'وقت',
    status: 'حالت',
    statusCompleted: 'مکمل شدہ',
    statusActive: 'جاری',

    // Buyers Khata
    khataTitle: 'خریداروں کا کھاتہ و وصولیاں',
    totalReceivables: 'کل وصولی (ادھار)',
    totalCashReceived: 'کل نقد موصول',
    markPaid: 'مکمل ادا شدہ کریں',
    paid: 'ادا شدہ',
    pending: 'بقایا',

    // History & Summary
    dailySummary: 'روزانہ منڈی کا خلاصہ',
    todayTurnover: 'آج کی کل فروخت',
    todayCommission: 'آج کا کمیشن منافع',
    todayCrates: 'کل کریٹ / بوریاں',
    todayLots: 'کل لاٹس',
    searchPlaceholder: 'زمیندار، خریدار یا جنس تلاش کریں...',

    // Settings
    settingsTitle: 'منڈی و دکان سیٹنگز',
    shopInfo: 'دکان کی معلومات',
    commissionSettings: 'کمیشن اور ریٹ ڈیفالٹس',
    defaultCommission: 'ڈیفالٹ کمیشن (%)',
    defaultMazdoori: 'ڈیفالٹ مزدوری فی کریٹ/بوری',
    defaultMarketFee: 'ڈیفالٹ مارکیٹ فیس فی یونٹ',
    defaultMunshiana: 'ڈیفالٹ منشیانہ (روپے)',
    currencySymbol: 'کرنسی کی علامت',
    soundEffects: 'آواز اور بٹن ساؤنڈ',
    saveSettings: 'سیٹنگز محفوظ کریں',
    restoreSampleData: 'ڈیمو ڈیٹا لوڈ کریں',
    dangerZone: 'تمام ڈیٹا صاف کریں',

    // Common
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    close: 'بند کریں',
    confirm: 'تصدیق',
    actions: 'اقدامات',
    viewDetails: 'تفصیلات دیکھیں',
    cratesUnitLabel: 'کریٹ/بوری',
    qty: 'تعداد',
    price: 'قیمت',
    quickPresets: 'تیز رفتار سلیکشن',
  },
  en: {
    // App Header & Branding
    appTitle: 'Mandi Bolli & Commission',
    appSubtitle: 'Vegetable & Fruit Commission Manager',
    shopDefaultName: 'Al-Hamra Fruit & Vegetable Commission Shop',
    shopAddressDefault: 'Shop #45, New Sabzi Mandi, Lahore',
    arhtiDefaultName: 'Malik M. Irfan (Commission Agent)',

    // Tabs
    tabBolli: 'Bolli & Lots',
    tabExpenses: 'Expense Slip',
    tabReceipt: 'Slip / Bill',
    tabKhata: 'Buyer Ledger',
    tabReports: 'Reports & Ledger',
    tabHistory: 'Daily History',
    tabSettings: 'Settings',

    // Reports Section
    reportsTitle: 'Mandi Detailed Reports & Analysis',
    reportsSubtitle: 'Breakdown and summaries by vendor, customer, date range, and commodity',
    reportByVendor: 'By Vendor',
    reportByCustomer: 'By Customer',
    reportByDate: 'By Date',
    reportByProduct: 'By Product',
    dateRange: 'Date Range',
    allTime: 'All Time',
    today: 'Today',
    yesterday: 'Yesterday',
    last7Days: 'Last 7 Days',
    thisMonth: 'This Month',
    customRange: 'Custom Range',
    fromDate: 'From Date',
    toDate: 'To Date',
    exportCSV: 'Export to CSV',
    printReport: 'Print Report',
    shareReportWA: 'Share WA Summary',
    avgRate: 'Average Rate',
    minRate: 'Min Rate',
    maxRate: 'Max Rate',
    totalUnitsSold: 'Total Units Sold',
    totalLotsCount: 'Total Lots',
    cashCollected: 'Cash Collected',
    creditOutstanding: 'Credit Balance',
    netVendorPayable: 'Net Vendor Payout',
    netArhtiCommission: 'Net Arhti Profit',
    noReportsFound: 'No records found matching the selected filters.',

    // Customer Directory & Connect
    customerDirectory: 'Customer Directory & Contacts',
    addCustomer: 'Save New Customer',
    editCustomer: 'Edit Customer',
    customerSaved: 'Customer saved successfully!',
    phoneCall: 'Call Phone',
    whatsapp: 'WhatsApp Message',
    recordPayment: 'Record Payment',
    paymentHistory: 'Payment History',
    saveCustomerPrompt: 'Save this customer to directory',
    shopOrMarket: 'Shop / Location',
    customerPhone: 'Phone Number',
    selectSavedCustomer: 'Select Saved Customer',

    // Custom Product ("Other")
    otherProduct: 'Other Commodity',
    enterCustomProduct: 'Enter custom fruit or vegetable name',
    productUrduLabel: 'Product Name (Urdu)',
    productEnLabel: 'Product Name (English)',
    selectIcon: 'Emoji Symbol',

    // Data Backup
    dataBackup: 'Data Backup & Restore',
    downloadBackup: 'Download JSON Backup',
    restoreBackup: 'Restore from JSON Backup',
    backupRestored: 'Backup restored successfully!',
    backupInvalid: 'Invalid backup file.',

    // Bolli / Lot Management
    newLot: 'New Lot Entry',
    activeLots: 'Active Bollis',
    completedLots: 'Completed Lots',
    viewAllLots: 'View All Lots',
    viewMore: 'View More',
    allLotsDirectory: 'All Lots Directory',
    filterAll: 'All',
    filterNotSold: 'Not Sold (Fresh)',
    filterPartiallySold: 'Partially Sold',
    filterFullySold: 'Fully Sold',
    filterDate: 'Date',
    filterToday: 'Today',
    filterYesterday: 'Yesterday',
    filterThisWeek: 'Last 7 Days',
    filterAllDates: 'All Dates',
    searchLotsPlaceholder: 'Search lot #, vendor, product, city, vehicle...',
    selectLot: 'Select for Bolli',
    lotStatus: 'Status',
    noLotsFound: 'No lots found',
    lotNumber: 'Lot #',
    vendor: 'Vendor / Farmer',
    vendorName: 'Vendor Name',
    vendorPhone: 'Phone',
    vendorCity: 'City / Area',
    saveVendorToDb: 'Save vendor to directory',
    selectSavedVendor: 'Regular Vendor:',
    saveCustomerToDb: 'Save customer to directory',
    walkInCustomer: 'Walk-in Customer',
    walkInPlaceholder: 'Walk-in Customer (Optional)',
    backToBolli: 'Back to Auction',
    back: 'Back',
    product: 'Product / Commodity',
    unitType: 'Unit Type',
    totalQuantity: 'Total Qty',
    remainingQuantity: 'Remaining Qty',
    soldQuantity: 'Sold Qty',
    vehicleNumber: 'Vehicle #',
    arrivalDate: 'Arrival Date',
    rate: 'Rate per Unit',
    startBolli: 'Start Bolli',
    bolliProgress: 'Bolli Progress',
    allSold: '100% Sold Out',
    inProgress: 'Bolli in Progress',

    // Units
    unitBori: 'Bori (Sacks)',
    unitTora: 'Tora (Bundles)',
    unitKainchi: 'Kainchi (Frames)',
    unitShopper: 'Shopper (Bags)',
    unitCrates: 'Crates',
    unitTheli: 'Theli (Bags)',
    unitPeti: 'Peti (Boxes)',
    unitKg: 'Kg',
    unitNag: 'Pieces',

    // Bolli Bidding Form
    addBidSale: 'Record Buyer Bid',
    buyerName: 'Buyer / Shopkeeper Name',
    buyerPhone: 'Phone',
    buyQuantity: 'Quantity Bought',
    bidRate: 'Bid Rate (Rs.)',
    totalAmount: 'Total Amount',
    paymentType: 'Payment Type',
    paymentCash: 'Cash Received',
    paymentCredit: 'Credit / Khata',
    paymentPartial: 'Partial Cash',
    confirmSale: 'Confirm Bid Sale',
    salesList: 'Sales Breakdown',
    noSalesYet: 'No bids recorded yet for this lot.',

    // Mandi Expense Slip (Replicating user's photo)
    expenseSlipTitle: 'Mandi Expense Slip & Meezan',
    expenseSlipSubtitle: 'Deductions, expenses and net payout calculation',
    grossTotal: 'Gross Total Sale',
    expensesSection: 'Deductions (اخراجات)',
    commission: 'Commission (کمیشن)',
    commissionAuto: 'Commission (% or Fixed)',
    kiraya: 'Freight / Kiraya (کرایہ)',
    mazdoori: 'Labor / Mazdoori (مزدوری)',
    munshiana: 'Munshiana (منشیانہ)',
    naqdAdvance: 'Cash Advance (نقد)',
    marketFee: 'Market Fee (مارکیٹ فیس)',
    customExpense: 'Other Deduction',
    addCustomExpense: 'Add Custom Deduction',
    expenseName: 'Expense Name',
    amount: 'Amount',
    totalExpenses: 'Total Deductions',
    meezan: 'Meezan (Net Payable to Vendor)',
    arhtiProfit: 'Agent Net Profit (Commission)',
    adjustManual: 'Manual Adjust',
    resetDefault: 'Auto Recalculate',

    // Receipt & Share
    printReceipt: 'Print Receipt',
    shareWhatsApp: 'Share on WhatsApp',
    copyReceipt: 'Copy Slip Text',
    receiptCopied: 'Receipt copied to clipboard!',
    pakkiParchi: 'Official Mandi Receipt',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    statusCompleted: 'Completed',
    statusActive: 'Active',

    // Buyers Khata
    khataTitle: 'Buyers Ledger & Receivables',
    totalReceivables: 'Total Pending (Credit)',
    totalCashReceived: 'Total Cash Received',
    markPaid: 'Mark Fully Paid',
    paid: 'Paid',
    pending: 'Pending',

    // History & Summary
    dailySummary: 'Daily Mandi Summary',
    todayTurnover: "Today's Gross Sales",
    todayCommission: 'Net Commission Profit',
    todayCrates: 'Total Crates/Bags',
    todayLots: 'Total Lots',
    searchPlaceholder: 'Search vendor, buyer or product...',

    // Settings
    settingsTitle: 'Mandi & Shop Settings',
    shopInfo: 'Shop Details',
    commissionSettings: 'Commission & Rate Defaults',
    defaultCommission: 'Default Commission (%)',
    defaultMazdoori: 'Default Labor per Unit (Rs.)',
    defaultMarketFee: 'Default Market Fee per Unit (Rs.)',
    defaultMunshiana: 'Default Munshiana (Rs.)',
    currencySymbol: 'Currency Symbol',
    soundEffects: 'Sound Effects',
    saveSettings: 'Save Settings',
    restoreSampleData: 'Load Demo Mandi Data',
    dangerZone: 'Clear All Data',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    actions: 'Actions',
    viewDetails: 'View Details',
    cratesUnitLabel: 'Crate/Bori',
    qty: 'Qty',
    price: 'Price',
    quickPresets: 'Quick Presets',
  },
};

export const unitLabels: Record<UnitType, { ur: string; en: string }> = {
  bori: { ur: 'بوری', en: 'Bori (Sack)' },
  tora: { ur: 'توڑہ / تورڑہ', en: 'Tora (Bundle)' },
  kainchi: { ur: 'کینچی', en: 'Kainchi (Frame)' },
  shopper: { ur: 'شاپر', en: 'Shopper (Bag)' },
  crates: { ur: 'کریٹ', en: 'Crates' },
  theli: { ur: 'تھیلی', en: 'Theli (Bag)' },
  peti: { ur: 'پیٹی', en: 'Peti (Box)' },
  kg: { ur: 'کلوگرام', en: 'Kg' },
  nag: { ur: 'نگ / عدد', en: 'Pieces' },
};

export interface ProductPreset {
  nameEn: string;
  nameUrdu: string;
  emoji: string;
  defaultUnit: UnitType;
  defaultAvgRate: number;
}

export const commonMandiProducts: ProductPreset[] = [
  { nameEn: 'آلو', nameUrdu: 'آلو', emoji: '🥔', defaultUnit: 'bori', defaultAvgRate: 3200 },
  { nameEn: 'پیاز', nameUrdu: 'پیاز', emoji: '🧅', defaultUnit: 'bori', defaultAvgRate: 3500 },
  { nameEn: 'ٹماٹر', nameUrdu: 'ٹماٹر', emoji: '🍅', defaultUnit: 'kainchi', defaultAvgRate: 2800 },
  { nameEn: 'سبز مرچ', nameUrdu: 'سبز مرچ', emoji: '🌶️', defaultUnit: 'shopper', defaultAvgRate: 2200 },
  { nameEn: 'بند گوبھی', nameUrdu: 'بند گوبھی', emoji: '🥬', defaultUnit: 'tora', defaultAvgRate: 1400 },
  { nameEn: 'پھول گوبھی', nameUrdu: 'پھول گوبھی', emoji: '🥦', defaultUnit: 'tora', defaultAvgRate: 1800 },
  { nameEn: 'سیب', nameUrdu: 'سیب', emoji: '🍎', defaultUnit: 'peti', defaultAvgRate: 4500 },
  { nameEn: 'کیلا', nameUrdu: 'کیلا', emoji: '🍌', defaultUnit: 'peti', defaultAvgRate: 1800 },
  { nameEn: 'آم', nameUrdu: 'آم', emoji: '🥭', defaultUnit: 'peti', defaultAvgRate: 5000 },
  { nameEn: 'کھیرا', nameUrdu: 'کھیرا', emoji: '🥒', defaultUnit: 'tora', defaultAvgRate: 1500 },
  { nameEn: 'بینگن', nameUrdu: 'بینگن', emoji: '🍆', defaultUnit: 'tora', defaultAvgRate: 1200 },
  { nameEn: 'لہسن', nameUrdu: 'لہسن', emoji: '🧄', defaultUnit: 'bori', defaultAvgRate: 6500 },
  { nameEn: 'ادرک', nameUrdu: 'ادرک', emoji: '🫚', defaultUnit: 'bori', defaultAvgRate: 8000 },
  { nameEn: 'لیموں', nameUrdu: 'لیموں', emoji: '🍋', defaultUnit: 'shopper', defaultAvgRate: 2400 },
];
