import { VendorLot, AppSettings, CustomerBuyer, SavedVendor } from '../types';
import { calculateLotSummary } from './calculations';

export const defaultSettings: AppSettings = {
  language: 'ur',
  currencySymbol: '₨',
  defaultCommissionPercent: 6.0,
  defaultMazdooriPerUnit: 30,
  unitMazdooriRates: {
    bori: 30,     // بوری: Rs. 30 per bori (as requested by user)
    tora: 25,     // توڑہ / تورڑہ: Rs. 25 per tora
    kainchi: 20,  // کینچی: Rs. 20 per kainchi
    shopper: 15,  // شاپر: Rs. 15 per shopper
    crates: 20,   // کریٹ: Rs. 20 per crate
    peti: 25,     // پیٹی: Rs. 25 per peti
    theli: 15,    // تھیلی: Rs. 15 per theli
    kg: 2,        // کلوگرام: Rs. 2 per kg
    nag: 5,       // نگ / عدد: Rs. 5 per piece
  },
  defaultMarketFeePerUnit: 5,
  defaultMunshiana: 30,
  shopNameUrdu: 'بسم اللہ فروٹ اینڈ سبزی کمیشن شاپ',
  shopNameEn: 'Bismillah Fruit & Vegetable Commission Shop',
  shopAddressUrdu: 'دکان نمبر 32، اے بلاک، نیو سبزی منڈی، لاہور',
  shopAddressEn: 'Shop #32, Block A, New Sabzi Mandi, Lahore',
  shopPhone: '+92 300 1234567',
  arhtiNameUrdu: 'حاجی محمد رفیق (آڑھتی)',
  arhtiNameEn: 'Haji Muhammad Rafeeq (Arhti)',
  soundEnabled: true,
  viewMode: 'mobile',
};

export const sampleVendors: SavedVendor[] = [
  {
    id: 'vendor-1',
    name: 'محمد اسلم زمیندار',
    phone: '0301-7654321',
    city: 'اوکاڑہ',
    notes: 'ٹماٹر کا باقاعدہ زمیندار',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
  {
    id: 'vendor-2',
    name: 'حاجی نذیر احمد',
    phone: '0345-4433221',
    city: 'سرگودھا',
    notes: 'پیاز اور آلو سپلائر',
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: 'vendor-3',
    name: 'چوہدری ریاض احمد',
    phone: '0300-4567890',
    city: 'ساہیوال',
    notes: 'سیب و موسمی پھل',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'vendor-4',
    name: 'ملک ظفر اقبال',
    phone: '0302-8877665',
    city: 'قصور',
    notes: 'ادرک، لہسن اور بند گوبھی',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

export const sampleCustomers: CustomerBuyer[] = [
  {
    id: 'cust-1',
    name: 'طارق سبزی فروش',
    phone: '0321-1122334',
    shopName: 'طارق سبزی سٹال',
    city: 'لاہور، گڑھی شاہو',
    notes: 'روزانہ نقد گاہک، کریٹ واپس کرتا ہے',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'cust-2',
    name: 'ندیم بھائی سبزی سٹال',
    phone: '0333-5566778',
    shopName: 'ندیم اینڈ سنز سبزی',
    city: 'لاہور، مغلپورہ',
    notes: 'ہفتہ وار ادھار کھاتہ کلیئر کرتا ہے',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'cust-3',
    name: 'عمران ہوٹل سپلائر',
    phone: '0300-9988776',
    shopName: 'روشن ہوٹل سپلائز',
    city: 'لاہور، گلبرگ',
    notes: 'بڑا خریدار، نقد ادائیگی',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'cust-4',
    name: 'ملک انور ہوتھول سیلر',
    phone: '0302-3344556',
    shopName: 'انور ٹریڈرز',
    city: 'قصور',
    notes: 'پیاز اور آلو کی بڑی خریداری',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'cust-5',
    name: 'بلال سبزی فروش',
    phone: '0312-8877665',
    shopName: 'مدینہ سبزی شاپ',
    city: 'لاہور، شادمان',
    notes: 'معتبر گاہک',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'cust-6',
    name: 'شاہد برادران',
    phone: '0344-9900112',
    shopName: 'شاہد برادران فروٹ شاپ',
    city: 'لاہور، انارکلی',
    notes: 'سیب و آم کا خریدار',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const sampleLots: VendorLot[] = [
  {
    id: 'lot-sample-1',
    lotNumber: 'LOT-2026-001',
    vendorName: 'محمد اسلم زمیندار',
    vendorPhone: '0301-7654321',
    vendorCity: 'اوکاڑہ',
    productName: 'Tomatoes',
    productUrdu: 'ٹماٹر (Tomato)',
    productEmoji: '🍅',
    unitType: 'crates',
    totalQuantity: 25,
    vehicleNumber: 'LES-4210 (شہزور)',
    arrivalDate: new Date().toISOString().slice(0, 10),
    status: 'active',
    vendorPaymentStatus: 'pending',
    sales: [
      {
        id: 'sale-1',
        buyerName: 'طارق سبزی فروش',
        buyerPhone: '0321-1122334',
        quantity: 3,
        ratePerUnit: 3000,
        totalAmount: 9000,
        paymentStatus: 'cash',
        paidAmount: 9000,
        notes: '3 کریٹ نقد وصول',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: 'sale-2',
        buyerName: 'ندیم بھائی سبزی سٹال',
        buyerPhone: '0333-5566778',
        quantity: 2,
        ratePerUnit: 2800,
        totalAmount: 5600,
        paymentStatus: 'credit',
        paidAmount: 0,
        notes: '2 کریٹ کھاتہ',
        timestamp: new Date(Date.now() - 2400000).toISOString(),
      },
      {
        id: 'sale-3',
        buyerName: 'عمران ہوٹل سپلائر',
        buyerPhone: '0300-9988776',
        quantity: 5,
        ratePerUnit: 2900,
        totalAmount: 14500,
        paymentStatus: 'cash',
        paidAmount: 14500,
        notes: '5 کریٹ اول مال',
        timestamp: new Date(Date.now() - 1200000).toISOString(),
      },
    ],
    expenses: {
      commission: {
        type: 'percentage',
        rate: 6,
        amount: 1746,
        enabled: true,
      },
      kiraya: {
        amount: 800,
        enabled: true,
        note: 'اوکاڑہ تا لاہور کرایہ',
      },
      mazdoori: {
        ratePerUnit: 20,
        amount: 500,
        enabled: true,
      },
      munshiana: {
        amount: 30,
        enabled: true,
      },
      naqdAdvance: {
        amount: 2000,
        enabled: true,
        note: 'ڈرائیور کو ڈیزل خرچ دیا گیا',
      },
      marketFee: {
        ratePerUnit: 5,
        amount: 125,
        enabled: true,
      },
      customExpenses: [
        {
          id: 'ce-1',
          nameUrdu: 'چھانٹی و لیبل',
          nameEn: 'Sorting & Label',
          amount: 150,
        },
      ],
    },
    summary: {
      totalSoldQuantity: 10,
      remainingQuantity: 15,
      grossSales: 29100,
      totalExpenses: 5351,
      netPayableToVendor: 23749,
      arhtiProfitCommission: 1776,
      percentSold: 40,
    },
    notes: 'سرخ ٹماٹر اول کوالٹی، 15 کریٹ باقی ہیں۔',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lot-sample-2',
    lotNumber: 'LOT-2026-002',
    vendorName: 'حاجی نذیر احمد',
    vendorPhone: '0345-4433221',
    vendorCity: 'سرگودھا',
    productName: 'Onions',
    productUrdu: 'پیاز (Onion)',
    productEmoji: '🧅',
    unitType: 'bori',
    totalQuantity: 10,
    vehicleNumber: 'FDN-9080 (ٹرک)',
    arrivalDate: new Date().toISOString().slice(0, 10),
    status: 'completed',
    vendorPaymentStatus: 'paid',
    vendorPaymentDate: new Date().toISOString().slice(0, 10),
    sales: [
      {
        id: 'sale-4',
        buyerName: 'ملک انور ہوتھول سیلر',
        buyerPhone: '0302-3344556',
        quantity: 4,
        ratePerUnit: 3500,
        totalAmount: 14000,
        paymentStatus: 'cash',
        paidAmount: 14000,
        timestamp: new Date(Date.now() - 14400000).toISOString(),
      },
      {
        id: 'sale-5',
        buyerName: 'بلال سبزی فروش',
        buyerPhone: '0312-8877665',
        quantity: 3,
        ratePerUnit: 3400,
        totalAmount: 10200,
        paymentStatus: 'credit',
        paidAmount: 0,
        timestamp: new Date(Date.now() - 10800000).toISOString(),
      },
      {
        id: 'sale-6',
        buyerName: 'شاہد برادران',
        buyerPhone: '0344-9900112',
        quantity: 3,
        ratePerUnit: 3600,
        totalAmount: 10800,
        paymentStatus: 'cash',
        paidAmount: 10800,
        timestamp: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
    expenses: {
      commission: {
        type: 'fixed',
        rate: 6.5,
        amount: 2270,
        enabled: true,
      },
      kiraya: {
        amount: 1200,
        enabled: true,
        note: 'ٹرک ڈرائیور کرایہ',
      },
      mazdoori: {
        ratePerUnit: 29,
        amount: 290,
        enabled: true,
      },
      munshiana: {
        amount: 30,
        enabled: true,
      },
      naqdAdvance: {
        amount: 0,
        enabled: false,
      },
      marketFee: {
        ratePerUnit: 5,
        amount: 50,
        enabled: true,
      },
      customExpenses: [],
    },
    summary: {
      totalSoldQuantity: 10,
      remainingQuantity: 0,
      grossSales: 35000,
      totalExpenses: 3840,
      netPayableToVendor: 31160,
      arhtiProfitCommission: 2300,
      percentSold: 100,
    },
    notes: 'تمام ۱۰ بوریاں نیلام مکمل ہو گئیں۔ پکی پرچی جاری کر دی گئی۔',
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lot-sample-3',
    lotNumber: 'LOT-2026-003',
    vendorName: 'چوہدری ریاض احمد',
    vendorPhone: '0300-4567890',
    vendorCity: 'ساہیوال',
    productName: 'Apples',
    productUrdu: 'سیب سوات (Apple)',
    productEmoji: '🍎',
    unitType: 'peti',
    totalQuantity: 20,
    vehicleNumber: 'LEA-5566 (مزدا)',
    arrivalDate: new Date(Date.now() - 86400000).toISOString().slice(0, 10), // yesterday
    status: 'completed',
    vendorPaymentStatus: 'paid',
    vendorPaymentDate: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    sales: [
      {
        id: 'sale-7',
        buyerName: 'شاہد برادران',
        buyerPhone: '0344-9900112',
        quantity: 10,
        ratePerUnit: 4600,
        totalAmount: 46000,
        paymentStatus: 'cash',
        paidAmount: 46000,
        notes: '10 پیٹی سیب نقد',
        timestamp: new Date(Date.now() - 86400000 + 3600000).toISOString(),
      },
      {
        id: 'sale-8',
        buyerName: 'طارق سبزی فروش',
        buyerPhone: '0321-1122334',
        quantity: 10,
        ratePerUnit: 4500,
        totalAmount: 45000,
        paymentStatus: 'credit',
        paidAmount: 0,
        notes: '10 پیٹی سیب ادھار',
        timestamp: new Date(Date.now() - 86400000 + 7200000).toISOString(),
      },
    ],
    expenses: {
      commission: {
        type: 'percentage',
        rate: 6.0,
        amount: 5460,
        enabled: true,
      },
      kiraya: {
        amount: 2500,
        enabled: true,
        note: 'سوات تا لاہور کرایہ',
      },
      mazdoori: {
        ratePerUnit: 25,
        amount: 500,
        enabled: true,
      },
      munshiana: {
        amount: 50,
        enabled: true,
      },
      naqdAdvance: {
        amount: 5000,
        enabled: true,
        note: 'پیشگی ڈرائیور',
      },
      marketFee: {
        ratePerUnit: 5,
        amount: 100,
        enabled: true,
      },
      customExpenses: [],
    },
    summary: {
      totalSoldQuantity: 20,
      remainingQuantity: 0,
      grossSales: 91000,
      totalExpenses: 13610,
      netPayableToVendor: 77390,
      arhtiProfitCommission: 5510,
      percentSold: 100,
    },
    notes: 'سیب سوات اعلیٰ گریڈ، کل فروخت 91000 روپے مکمل۔',
    createdAt: new Date(Date.now() - 86400000 - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 + 10000000).toISOString(),
  },
];

// Initialize lots with dynamic calculation
export function getInitialLots(): VendorLot[] {
  return sampleLots.map((lot) => {
    const summary = calculateLotSummary(lot.totalQuantity, lot.sales, lot.expenses);
    return {
      ...lot,
      summary,
    };
  });
}
